
spring:

  application:
    name: teacher_management-system-web
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  ai:
    openai:
      api-key: 123
      base-url: http://10.1.1.84:12346
      chat:
        options:
          model: azure-openai/gpt-4.1
          temperature: 0.2
          timeout: 30s

      embedding:
        options:
          model: azure-openai/text-embedding-3-small
          dimensions: 1536

    vectorstore:
      pgvector:
        chunk-size: 300
        chunk-overlap: 50


jwt:
    secret: 12345678901234567890123456789012
    expiration-ms: 86400000

server:
    port: 8080
mybatis-plus:
  type-handlers-package: com.teacher.domain.handler

  #    url: jdbc:postgresql://localhost:5432/teacher_management
  #    username: postgres
  #    password: 123456